version: 1

sequences:
  - protein:
      id: A
      sequence: QVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKGLEWVSAISGSGGSTYYADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKVSYLSTASSLDYWGQGTLVTVSS
  - ligand:
      id: B
      smiles: "Nc1ccn([C@H]2C[C@H](O)[C@@H](COP(O)(=O)OP(O)(=O)OP(O)(O)=O)O2)c(=O)n1"

# Target: Design nanobody to bind dCTP specifically
# Reference PDB: 3T04 (DNA polymerase with dCTP)
